- link:
    ~/.config/Code/User/settings.json: vscode/settings.json

- shell:
    - command: script/code-import-ext
      stdout: true
      stderr: true
      description: Install VS Code extensions
